refactor: migrate no-wait-for-snapshot to v4
testing-library/eslint-plugin-testing-library pull request #271
Opened 2020-12-11 22:30 UTC by gndelia

This PR migrates the `no-wait-for-snapshot` rule to use the new helper, as part of #198

2020-12-11 22:41 UTC, Belco90 requested changes
Really simple now! Just a small change and we are ready to go.

2020-12-11 22:41 UTC, Belco90 commented on lib/rules/no-wait-for-snapshot.ts
> +    function getClosestAsyncUtil(node: TSESTree.Node) {
I think the method is fine here for now, it seems really specific. However, there is one thing which can be reused from detection helpers: `ASYNC_UTILS.includes(callExpression.callee.name)` should be replaced by `helpers.isAsyncUtil(callExpression.callee)`

2020-12-12 17:43 UTC, gndelia commented on lib/rules/no-wait-for-snapshot.ts
> +    function getClosestAsyncUtil(node: TSESTree.Node) {
solved in https://github.com/testing-library/eslint-plugin-testing-library/pull/271/commits/e0bf288c94e6442344a44eebe2f2795fc0435a24

2020-12-12 17:45 UTC, Belco90 approved these changes

2020-12-12 17:46 UTC, Belco90 commented
Waiting for green CI and I'll merge it 🚀

2020-12-13 10:11 UTC, merged