fix: add no-await-sync-events exception for userEvent.keyboard
testing-library/eslint-plugin-testing-library pull request #283
Opened 2021-03-13 19:13 UTC by ph-fritsche

Added exception for the new API proposed in https://github.com/testing-library/user-event/pull/581

Note that with the change `userEvent.type` (and `userEvent.keyboard`) will actually return no Promise if the `delay` is not `>0` so that the typing and the actual return value will match.

Further it might be worth discussing if this rule should be disabled for `.ts` and `.tsx` files as `ts(80007)` and `@typescript-eslint/await-thenable` already warn here and currating a manual list has no benefits when there already are warnings based on the type.

2021-03-15 08:17 UTC, Belco90 commented
Hey @ph-fritsche, thanks for your contribution! We need to wait until https://github.com/testing-library/user-event/pull/581 gets merged.

Meanwhile, could you add some additional tests to check `userEvent.keyboard` is reported or not as intended?

About disabling the rule in TS environments: the plugin won't detect that for now, so it's up to the user to decide if they want to enable or disable the rule.

2021-03-17 00:49 UTC, MichaelDeBoey requested changes

2021-03-17 00:49 UTC, MichaelDeBoey commented on lib/rules/no-await-sync-events.ts
> +        if (!(node.name === 'userEvent' && (methodNode.name === 'type' || methodNode.name === 'keyboard') && withDelay)) {
```suggestion
        if (!(node.name === 'userEvent' && ['type', 'keyboard'].includes(methodNode.name) && withDelay)) {
```

2021-03-18 20:21 UTC, gndelia reviewed
should we update a test to include the `keyboard` method ? 🤔

2021-03-20 13:57 UTC, Belco90 commented
I just realized this rule is still [pending to be refactored for v4](https://github.com/testing-library/eslint-plugin-testing-library/issues/198). @ph-fritsche I can include `userEvent.keyboard` there when I refactor it. What do you think?

2021-03-20 22:05 UTC, ph-fritsche commented
@Belco90 I've added the changes necessary. Should be ready to be merged now. :smiley:

2021-03-21 09:57 UTC, Belco90 commented
LGTM, thanks for your PR and nice work adding this new feature to `userEvent` 🚀

2021-03-21 10:00 UTC, Belco90 approved these changes

2021-03-21 10:04 UTC, merged

2021-03-24 12:02 UTC, Belco90 commented
@ph-fritsche sorry mate, I forgot to add you as a contributor!

@all-contributors please add @ph-fritsche for code

2021-03-24 12:02 UTC, Belco90 commented
@all-contributors please add @ph-fritsche for code