chore: add tests for Node 16
testing-library/eslint-plugin-testing-library pull request #350
Opened 2021-04-21 14:41 UTC by MichaelDeBoey

2021-04-21 15:00 UTC, Belco90 requested changes
I'm afraid this will suffer the same issue with node v15, since it uses npm v7 which installs peer dependencies and leads to some errors. This has to be investigated and fixed before being able to merge it.

2021-05-18 15:31 UTC, Belco90 commented
Hey @MichaelDeBoey! Could you update this branch with `main` to check if the peer dependencies issue has been solved, please?

2021-05-18 16:49 UTC, MichaelDeBoey commented
@Belco90 All tests are green 🥳🎉

2021-05-18 17:37 UTC, Belco90 approved these changes

2021-05-18 17:38 UTC, merged