chore: create bug report form
testing-library/eslint-plugin-testing-library pull request #428
Opened 2021-07-21 10:14 UTC by HonkingGoose

Work in progress.

Go to https://github.com/HonkingGoose/eslint-plugin-testing-library/blob/patch-2/.github/ISSUE_TEMPLATE/bug_report.yml to see a rendered preview of the bug report form.

2021-07-21 10:18 UTC, HonkingGoose commented
I'm ready for a round of review on this draft. Let me know what you think of it.

I need help with some placeholder text, so if you can suggest a better text, please do so. 😉

2021-07-22 07:56 UTC, HonkingGoose commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      placeholder: TODO ADD EXAMPLE OF A RULE
```suggestion
      placeholder: Tip: check your `.eslintrc` for rules.
```

2021-07-22 07:56 UTC, HonkingGoose commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      placeholder: You can find your ESLint configuration in these files TODO ADD LIST OF VALID FILENAMES
```suggestion
      placeholder: Tip: you can find your ESLint configuration in the `.eslintrc` file.
```

2021-07-22 08:47 UTC, MichaelDeBoey requested changes

2021-07-22 08:47 UTC, MichaelDeBoey commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: Rules(s) affected
```suggestion
      label: Rule(s) affected
```

2021-07-22 08:47 UTC, MichaelDeBoey commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      required: true
```suggestion
      required: false
```

2021-07-22 08:53 UTC, MichaelDeBoey approved these changes

2021-07-22 09:30 UTC, Belco90 approved these changes
It's a really good issue form! I think we got everything covered. Thanks again!

2021-07-22 09:30 UTC, merged

2021-07-22 09:31 UTC, HonkingGoose commented
Hooray! Thank you for reviewing and merging my work. 😄