feat: await-async-event
testing-library/eslint-plugin-testing-library pull request #652
Opened 2022-09-29 02:49 UTC by skovy

> ⚠️ Work in progress, not ready to merge but opening for early feedback or help to complete

## Checks

- [x] I have read the [contributing guidelines](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/CONTRIBUTING.md).
- [ ] If some rule is added/updated/removed, I've regenerated the rules list (`npm run generate:rules-list`)
- [ ] If some rule meta info is changed, I've regenerated the plugin shared configs (`npm run generate:configs`)

## Changes

- (Need to do) Update the existing `await-fire-event` rule to become the `await-async-event` rule
- Support both user event and fire event via configuration, with the default being user event

## Context

Resolves https://github.com/testing-library/eslint-plugin-testing-library/issues/626

2022-09-29 10:47 UTC, Belco90 reviewed
Thanks for taking care of this! I left some comments.

2022-09-29 10:47 UTC, Belco90 commented on lib/rules/await-fire-event.ts
> +const EVENT_MODULES = ['fireEvent', 'userEvent'] as const;
We have `EVENTS_SIMULATORS` exported in `utils`. Any problem with reusing that one?

2022-09-29 10:47 UTC, Belco90 commented on lib/rules/await-fire-event.ts
> +						type: 'string',
Sorry, I think I didn't specify this really well in the original ticket. The idea is that this is a list accepting either "fire-event", "user-event", or both!

Frameworks like Vue Testing Library will need to report both, so they'll need to set this option to `["fire-event", "user-event"]`.

By default, it should be just `["user-event"]`

It should be fairly easy to adapt your current code tho.

2022-09-29 15:26 UTC, skovy commented
Thanks for the feedback, I'll take a look at those comments! Forgot about draft PRs, thanks for updating that too 🤦‍♂️

2022-09-30 17:36 UTC, Belco90 requested changes
Great job @skovy! I added a few comments, but should be easy to fix. I think after that it should be ready to go 🚀

2022-09-30 17:36 UTC, Belco90 commented on README.md
> +| [`await-async-event`](./docs/rules/await-async-event.md)                             | Enforce promises from `fireEvent` methods to be handled                                      |     | ![vue-bad
Have you generated this with the scripts provided in the project? They are mentioned in the PR description, so this table is automatically generated from rules meta info. The description and badges for this one doesn't seem correct.

2022-09-30 17:36 UTC, Belco90 commented on docs/rules/await-async-event.md
> +	await userEvent.tripleClick(getByText('Click me'));
When handling several promises with `Promise.all`, it's not necessary to handle the inner ones, but only the outer one. Not sure if this is inherited from the previous docs, but it's incorrect. Could you fix this, please?

2022-09-30 17:36 UTC, Belco90 commented on docs/rules/await-async-event.md
> +- `eventModule`: which event module should be linted for async event methods (`userEvent` and/or `fireEvent`). Defaults to `userEvent` which should be used after v14. `fireEvent` should only be used
Could you specify the expected type? Which basically is string or array of strings.

2022-09-30 17:36 UTC, Belco90 commented on lib/rules/await-async-event.ts
> +				marko: ['error', { eventModule: 'fireEvent' }],
Vue and Marko actually need both by default: we are aiming for userEvent v14 by default, and fireEvent is async in those frameworks:

```suggestion
				vue: ['error', { eventModule: ['fireEvent', 'userEvent'] }],
				marko: ['error', { eventModule: ['fireEvent', 'userEvent'] }],
```

2022-10-02 09:00 UTC, Belco90 requested changes
Last request! Can you add some tests without setting the option so it takes the default value? This way we explicitly test the default options. Duplicating existing tests just without the option property is fine.

2022-10-02 18:53 UTC, Belco90 approved these changes

2022-10-02 18:56 UTC, merged