ci: fix smoke test's npm setup
testing-library/eslint-plugin-testing-library pull request #714
Opened 2023-01-03 06:44 UTC by AriPerkkio

## Checks

- [x] I have read the [contributing guidelines](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/CONTRIBUTING.md).

## Changes

- chore(dev-deps): update eslint-remote-tester-repositories
  - Updates `eslint-remote-tester-repositories` to new major version. No breaking changes. API is now considered as stable
- ci: fix smoke test's npm setup
  - Workflow seemed to be crashing due to some Node/NPM setup issues. Copied setup steps from `pipeline.yml`

2023-01-03 07:19 UTC, MichaelDeBoey requested changes

2023-01-03 07:19 UTC, MichaelDeBoey commented on .github/workflows/smoke-test.yml
> +
We already run `npm install` in the next step

```suggestion
```

2023-01-03 15:06 UTC, Belco90 approved these changes

2023-01-05 18:04 UTC, merged

2023-01-05 18:04 UTC, Belco90 commented
Thanks @AriPerkkio!!