Update `testing-library/prefer-presence-queries` rule to support custom react-native matcher `toBeOnTheScreen`
testing-library/eslint-plugin-testing-library pull request #844
Opened 2023-11-17 17:45 UTC by retyui

## Checks

- [x] I have read the [contributing guidelines](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/CONTRIBUTING.md).

## Changes

React Native Testing Library recommend to use this eslint plugin: https://callstack.github.io/react-native-testing-library/docs/eslint-plugin-testing-library 
React Native Testing Library has custom matchers: https://callstack.github.io/react-native-testing-library/docs/jest-matchers#tobeonthescreen

this PR adding support for support for that matsher `toBeOnTheScreen`

```tsx
expect(screen.queryByText('button')).toBeOnTheScreen(); // No error :(

expect(screen.queryByText('button')).toBeInTheDocument(); // Error: testing-library/prefer-presence-queries
```

## Context

...

2023-11-17 19:02 UTC, Belco90 requested changes
Thanks for your contribution. Can you add some valid and invalid tests, please? Thanks.

2023-11-17 19:21 UTC, retyui commented
> Thanks for your contribution. Can you add some valid and invalid tests, please? Thanks.

ready

2023-11-20 12:25 UTC, retyui commented
@Belco90 can you review it again?

2023-11-21 07:26 UTC, Belco90 approved these changes

2023-11-21 07:26 UTC, merged