chore: remove `eslint-config-kentcdodds`
testing-library/eslint-plugin-testing-library pull request #856
Opened 2023-12-12 17:47 UTC by lesha1201

## Checks

- [x] I have read the [contributing guidelines](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/CONTRIBUTING.md).

## Context

These changes were initially introduced in https://github.com/testing-library/eslint-plugin-testing-library/pull/852

2023-12-13 12:31 UTC, Belco90 requested changes

2023-12-13 12:31 UTC, Belco90 commented on .eslintrc.js
> +						extensions: ['.js', '.jsx', '.ts', '.tsx'],
We don't need jsx and tsx in this repo.

2023-12-14 07:20 UTC, lesha1201 commented on .eslintrc.js
> +						extensions: ['.js', '.jsx', '.ts', '.tsx'],
Done

2023-12-14 07:22 UTC, lesha1201 commented
@Belco90 By the way, do you have some conventions/rules in mind that you want to enforce? I would like to improve ESLint setup  later but not very familiar with the codebase yet and its conventions.

2023-12-14 07:50 UTC, lesha1201 commented
@Belco90 CI will fail for Node v12 because of this https://github.com/testing-library/eslint-plugin-testing-library/pull/857#issuecomment-1855338100. Previously, `eslint-config-kentcdodds` were taking precedence over our `extends: ['plugin:jest/recommended']` and because of that ESLint were using an old version of `eslint-plugin-jest` which support Node.js v12. But now it uses our version of `eslint-plugin-jest` which doesn't support Node.js v12.

![image](https://github.com/testing-library/eslint-plugin-testing-library/assets/10157660/ebbd85be-c4cb-46f2-bf88-202f25664fc2)

2024-01-12 10:41 UTC, Belco90 commented
> @Belco90 By the way, do you have some conventions/rules in mind that you want to enforce? I would like to improve ESLint setup later but not very familiar with the codebase yet and its conventions.

I have something in mind, but let's do that in a follow-up PR.

2024-01-12 10:45 UTC, Belco90 approved these changes
Sorry for the late response! The Christmas break was way busier than I thought, so I'm slowly coming back to this now.

2024-01-12 10:55 UTC, merged

2024-01-12 10:56 UTC, Belco90 commented
@all-contributors please add @lesha1201 for maintenance