feat(await-async-query):  add auto-fix
testing-library/eslint-plugin-testing-library pull request #917
Opened 2024-07-26 14:58 UTC by neriyarden

## Checks

- [x] I have read the [contributing guidelines](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/CONTRIBUTING.md).

## Changes

- Add a fixer for the await-async-query rule (add 'await ' before the query)
- Fix some tests names from "An invalid test" to "A valid test" in valid test cases

## Context
Fixes #914 
also some of #202

2024-10-17 22:06 UTC, MichaelDeBoey approved these changes

2024-10-17 22:06 UTC, MichaelDeBoey commented on lib/rules/await-async-queries.ts
> +								},
```suggestion
								fix: (fixer) =>
									references.map((ref) =>
										fixer.insertTextBefore(ref.identifier, 'await ')
									),
```

2024-10-19 01:25 UTC, MichaelDeBoey approved these changes

2024-10-19 01:58 UTC, MichaelDeBoey approved these changes

2025-03-12 06:30 UTC, neriyarden commented
@Belco90 @MichaelDeBoey
Any update about this PR? Will it be merged?

2025-05-05 07:16 UTC, Belco90 requested changes

2025-05-05 07:16 UTC, Belco90 commented on lib/rules/await-async-queries.ts
> +										identifierNode.parent.object.name === 'screen'
Does it really matter if the parent object is `screen`? I think it should work no matter what the name of its parent is.

For example:

```js
test("An example test", async () => {
  const view = render(<Component />)
  const button = view.findByText('submit')
});
```

In this case, `view.findByText` wouldn't be autofixed, but it should. Can you add this scenario to the tests, and adjust the rule fix accordingly?

2025-05-05 07:16 UTC, Belco90 commented on lib/rules/await-async-queries.ts
> +						},
Nice one!

2025-08-12 05:36 UTC, closed without merging

2025-08-12 05:38 UTC, Belco90 commented
Closing due to inactivity. Feel free to reopen to get it merged, fixing the requested changes.