feat(no-await-sync-queries): add auto-fix
testing-library/eslint-plugin-testing-library pull request #919
Opened 2024-07-27 15:17 UTC by neriyarden

## Checks

- [x] I have read the [contributing guidelines](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/CONTRIBUTING.md).

## Changes

 - Add auto-fix for the no-await-sync-queries rule (remove 'await ' before sync queries)

## Context
Fixes an item in #202

2024-10-11 03:29 UTC, G-Rath requested changes
this looks good but you're assuming there will always be a space after the `await` which means `await(getByIcon('search'))` will error.

I'm pretty sure you can fix this by just removing the space, since the fixer doesn't need to care about the styling of the output

2024-10-12 10:23 UTC, neriyarden commented
@G-Rath Good catch and thanks for the review 🙂 
I removed the space after the `await` in the fixer and updated the tests.
I also added a test cade for the example you gave (`await(getByIcon('search'))`)

Let me know what you think:)

2024-10-14 19:33 UTC, G-Rath approved these changes
looks good to me!

2024-10-17 22:11 UTC, MichaelDeBoey approved these changes

2024-10-19 01:27 UTC, MichaelDeBoey submitted a review, later dismissed

2025-03-12 06:29 UTC, neriyarden commented
@Belco90 @MichaelDeBoey
Any update about this PR? Will it be merged?

2025-04-30 06:29 UTC, Belco90 commented
Hi @neriyarden. I'll try to get this merged soon, thanks for your patience!

2025-04-30 06:30 UTC, Belco90 commented on README.md
> +| [no-await-sync-queries](docs/rules/no-await-sync-queries.md)                     | Disallow unnecessary `await` for sync queries                                                | ![badge-angular][]
I think there are some conflicts here, can you resolve that @neriyarde?

2025-05-03 16:29 UTC, neriyarden commented on README.md
> +| [no-await-sync-queries](docs/rules/no-await-sync-queries.md)                     | Disallow unnecessary `await` for sync queries                                                | ![badge-angular][]
Yes, thanks.

Im getting some type errors in these files when im trying to solve the conflicts:
- lib/create-testing-library-rule/index.ts
- lib/rules/await-async-utils.ts
- tools/generate-configs/utils.ts
- lib/utils/types.ts
- lib/utils/compat.ts


I don't remember doing any changes in these files but i still get type errors.

Since I don't know these changes and i don't want to break anythig, can I get some help solving these from someone who's familiar with these files and type?

2025-08-12 05:36 UTC, closed without merging

2025-08-12 05:38 UTC, Belco90 commented
Closing due to inactivity. Feel free to reopen to get it merged. First, we need to tackle comments from #917